chore(linter): update golangci.yaml
lasiar/canonicalheader pull request #46
Opened 2024-05-15 19:39 UTC by lasiar

add new linters

See: 42

2024-05-15 19:55 UTC, ccoVeille requested changes
Dupwords should be enabled, it costs nothing and detects typos

gci should be enabled with the following linter settings

- standard
- default
- localmodule

2024-05-15 19:59 UTC, ccoVeille reviewed
There is no reason to set revive confidence at 0.1 instead of default value 0.8

2024-05-15 19:59 UTC, ccoVeille commented on .golangci.yaml
> +    - mirror
Mirror should be enabled

2024-05-15 19:59 UTC, ccoVeille commented on .golangci.yaml
> -        arguments:
Commenting a random line

Didn't revive support more linter?

2024-05-15 20:30 UTC, ccoVeille commented
Here is a PR I made for pman

https://github.com/theredditbandit/pman/pull/25

You can see the linters I used. I enabled all revive and disabled only a few, I'm unsure if it was a good idea for maintenance but the results were impressive

2024-05-17 20:02 UTC, lasiar commented
> Dupwords should be enabled, it costs nothing and detects typos
> 
> gci should be enabled with the following linter settings
> 
> * standard
> * default
> * localmodule

Done

2024-05-17 20:04 UTC, lasiar commented
> Here is a PR I made for pman
> 
> [theredditbandit/pman#25](https://github.com/theredditbandit/pman/pull/25)
> 
> You can see the linters I used. I enabled all revive and disabled only a few, I'm unsure if it was a good idea for maintenance but the results were impressive

I enable all linters from revive
https://github.com/lasiar/canonicalheader/blob/e73e1bb759da822df08218cdbf0db7b4f53248c6/.golangci.yaml#L375-L375

2024-05-17 20:05 UTC, lasiar commented
@ccoVeille, I'm sorry for long reply

I'm busy IRL

2024-05-18 07:07 UTC, ccoVeille approved these changes

2024-05-18 09:16 UTC, merged